<?php
Asset::css('css/bootstrap.min');
Asset::css('css/jquery-ui.min');
Asset::css('css/fa/css/all.min');
Asset::css('css/main');
Asset::css('css/offcanvas-sidebar');
Asset::js('js/jquery.min');
Asset::js('js/jquery-ui.min');
Asset::js('js/bootstrap.bundle.min');